//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sodo_Phonghop_Hoitruong.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLPHHTEntities1 : DbContext
    {
        public QLPHHTEntities1()
            : base("name=QLPHHTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhienHop> PhienHops { get; set; }
        public virtual DbSet<ThongTinGhe> ThongTinGhes { get; set; }
    }
}
