//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sodo_Phonghop_Hoitruong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienHop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhienHop()
        {
            this.ThongTinGhes = new HashSet<ThongTinGhe>();
        }
    
        public int IDPhienHop { get; set; }
        public string TenPhienHop { get; set; }
        public string Mota { get; set; }
        public string HinhThuc { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> ChieuDoc { get; set; }
        public Nullable<int> ChieuNgang { get; set; }
        public Nullable<int> SoDay { get; set; }
        public Nullable<int> SoHangMoiDay { get; set; }
        public string SoGheMoiHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongTinGhe> ThongTinGhes { get; set; }
    }
}
