//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sodo_Phonghop_Hoitruong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGhe
    {
        public Nullable<int> STT { get; set; }
        public string IDGhe { get; set; }
        public string TenGhe { get; set; }
        public string HoTen { get; set; }
        public string ChucDanh { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> DoUuTien { get; set; }
        public int IDPhienHop { get; set; }
    
        public virtual PhienHop PhienHop { get; set; }
    }
}
